### ISSUE TITLE
Help:How to test scripts without Application data

### ISSUE THREAD

**Issue by ghost** [tlsfuzzer/tlsfuzzer#756]
is there any option to test scripts without application data?

**Comment by tomato42** [comment]
I'm not sure if I understand the question... 
 * "Is it possible to have test scripts that don't send Application Data?" — yes
 * "Is it possible to run existing scripts from `scripts/` directory in a way that they won't send Application Data?" — not easily, you have to modify the scripts to remove or change the nodes used for processing Application Data to be no-ops
 * "Is it possible to test all features of TLS without sending Application Data?" — no, there are many situations where the interaction between Application Data records and other record types is the purpose of the test, also, especially in TLS 1.3, you can't be sure that the connection was negotiated correctly without sending and receiving Application Data

That being said, why you don't want to send Application Data in the script? While the scripts default to HTTP, it's because most TLS implementations have a [test server](https://github.com/tlsfuzzer/tlsfuzzer/wiki/Server-setup) with a minimal HTTP implementation that can be used for testing. But basically any protocol in which client and server both send data can be used.

**Comment by skommula96** [comment]
Basically our application doesn't support HTTP.
is there any way that I can bypass application data?

Thanks in advance

**Comment by tomato42** [comment]
> is there any way that I can bypass application data?

yes, by editing the test scripts

but it's unlikely you want to remove Application Data nodes completely, as many tests need exchange of application data to either trigger errors or to verify successful connections

So, if you have a custom TLS implementation you want to test, I strongly suggest implementing a simple echo server (that's really what's needed for almost all tests) as that will be easier than modifying all the scripts.
But if you want to test an integrated application with a TLS server (which is quite valid, even if you use implementations like OpenSSL, given how invasive the application callbacks can be) you will need to modify the existing test scripts.
